project:
  type: website

website:
  title: "E155 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Labs"
        menu:
          - text: "Lab 1"
            href: blog.qmd
          - text: "Lab 2"
            href: blog.qmd
          - text: "Lab 3"
            href: blog.qmd
      - href: blog.qmd
        text: Blog
      - href: resources.qmd
        text: Resources

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
