project:
  type: website

website:
  title: "E155 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Labs"
        href: labs/labs.qmd
        menu:
          - text: "Lab 1"
            href: labs/lab1/lab1.qmd
          - text: "Lab 2"
            href: blog.qmd
          - text: "Lab 3"
            href: blog.qmd
      - href: resources.qmd
        text: Resources
      - href: blog.qmd
        text: Blog

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor:
  render-on-save: true
