---
title: "E155 Labs"
listing:
  contents: labs
  type: default
---

## [Lab 1: FPGA and MCU Setup and Testing](lab1/lab1.qmd)
In this lab, the microcontroller and FPGA development board we will use for the continuation of this semester of E155 was soldered and assembled. We verified it was working correctly by uploading some demo code to make an onboard LED blink at $1$ Hz.

The rest of the lab consisted of making some combinational logic to turn on onboard LEDs in addition to making another onboard LED blink at $2.4$ Hz and more combinational logic to display a digit in a 7-Segment-Display depending on the binary input.

## [Lab 2: Multiplexed 7-Segment Display](lab2/lab2.qmd)
TO-DO

## [Lab 3: Keypad Scanner](lab3/lab3.qmd)
TO-DO

## [Lab 4: Digital Audio](lab4/lab4.qmd)
TO-DO

## [Lab 5: Interrupts](lab5/lab5.qmd)
TO-DO

## [Lab 6: The Internet of Things and Serial Peripheral Interface Learning](lab6/lab6.qmd)
TO-DO

## [Lab 7: The Advanced Encryption Standard](lab7/lab7.qmd)
TO-DO